### ISSUE TITLE
error make install thank a lot

### ISSUE THREAD

**Issue by michele-radi** [TheWandrr/vedirect_to_mqtt#5]
sudo make install
cc    -c -o vedirect_to_mqtt.o vedirect_to_mqtt.c
vedirect_to_mqtt.c:13:10: fatal error: wiringSerial.h: File o directory non esistente
   13 | #include <wiringSerial.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<incorporato>: vedirect_to_mqtt.o] Errore 1

**Comment by TheWandrr** [comment]
I thought this library was installed by default, but maybe not. There are a bunch of tutorials on installing it such as (not tested!):

https://tutorials-raspberrypi.com/installing-wiringpi-and-pin-allocation/

Please check if 'wiringPi' is installed, if not then install it. Follow up here with the result. If this fixed it I'll add a note regarding the dependency.

.
